# BMM Module Configuration
# Project: {{ cookiecutter.project_name }}

project_name: {{ cookiecutter.project_name }}
user_skill_level: intermediate
planning_artifacts: "{project-root}/_bmad-output/planning-artifacts"
implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
project_knowledge: "{project-root}/docs"

# Core Configuration Values
user_name: {{ cookiecutter.bmad_user_name }}
communication_language: English
document_output_language: English
output_folder: "{project-root}/_bmad-output"
