[theme]
primaryColor = "#28a745"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C2128"
textColor = "#FAFAFA"
font = "monospace"

[server]
runOnSave = false

[client]
toolbarMode = "minimal"
